# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4C5CVr9ozhWx3kwAfY16Utb7SuXIJP3
"""

# Function to classify temperature
def classify_temperature(temp):
    if temp < 18:
        return "Cold"
    elif temp <= 28:
        return "Normal"
    else:
        return "Hot"

# Function to calculate statistics
def calculate_stats(temps):
    avg = sum(temps) / len(temps)
    highest = max(temps)
    lowest = min(temps)
    return avg, highest, lowest

# Function to display report
def display_report(temps, counts):
    avg, highest, lowest = calculate_stats(temps)

    print("\nTemperature Summary")
    print("Average Temperature =", round(avg, 2))
    print("Highest Temperature =", highest)
    print("Lowest Temperature =", lowest)

    print("\nCondition Count")
    print("Hot =", counts["Hot"])
    print("Normal =", counts["Normal"])
    print("Cold =", counts["Cold"])

    print("\nSuggested Action")
    if counts["Hot"] > 0:
        print("Fan ON")
    if counts["Cold"] > 0:
        print("Heater ON")
    if counts["Hot"] == 0 and counts["Cold"] == 0:
        print("No action required")

# Main program
temps = []
counts = {"Hot": 0, "Normal": 0, "Cold": 0}

n = int(input("Enter number of readings: "))

for i in range(n):
    temp = float(input("Enter temperature: "))
    temps.append(temp)

    condition = classify_temperature(temp)
    counts[condition] += 1

display_report(temps, counts)